# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: unicron.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\runicron.proto\" \n\x10\x41udiolizeRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"\"\n\x11\x41udiolizeResponse\x12\r\n\x05\x61udio\x18\x01 \x01(\x0c\"\x1f\n\x0eTextifyRequest\x12\r\n\x05\x61udio\x18\x01 \x01(\x0c\"\x1f\n\x0fTextifyResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\"2\n\x11SimilarityRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0f\n\x07\x61nswers\x18\x02 \x03(\t\"(\n\x12SimilarityResponse\x12\x12\n\nsimilarity\x18\x01 \x01(\x01\x32\xa2\x01\n\x07Unicron\x12\x32\n\taudiolize\x12\x11.AudiolizeRequest\x1a\x12.AudiolizeResponse\x12,\n\x07textify\x12\x0f.TextifyRequest\x1a\x10.TextifyResponse\x12\x35\n\nsimilarity\x12\x12.SimilarityRequest\x1a\x13.SimilarityResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'unicron_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_AUDIOLIZEREQUEST']._serialized_start=17
  _globals['_AUDIOLIZEREQUEST']._serialized_end=49
  _globals['_AUDIOLIZERESPONSE']._serialized_start=51
  _globals['_AUDIOLIZERESPONSE']._serialized_end=85
  _globals['_TEXTIFYREQUEST']._serialized_start=87
  _globals['_TEXTIFYREQUEST']._serialized_end=118
  _globals['_TEXTIFYRESPONSE']._serialized_start=120
  _globals['_TEXTIFYRESPONSE']._serialized_end=151
  _globals['_SIMILARITYREQUEST']._serialized_start=153
  _globals['_SIMILARITYREQUEST']._serialized_end=203
  _globals['_SIMILARITYRESPONSE']._serialized_start=205
  _globals['_SIMILARITYRESPONSE']._serialized_end=245
  _globals['_UNICRON']._serialized_start=248
  _globals['_UNICRON']._serialized_end=410
# @@protoc_insertion_point(module_scope)
